project: pu_graphs
entity: hse-jbr-ai
name: std-sweep

program: main.py

metric:
  name: mrr_filtered_epoch/test
  goal: maximize

method: grid
parameters:
  seed:
    values:
      - 4
      - 8
      - 15
      - 16
      - 23
      - 42
