run_name: dist-mult

model: dist-mult
seed: 19
is_debug: True

optimizer:
  _target_: torch.optim.Adam
  _mode_: partial
  lr: 0.0001

batch_size: 64
eval_batch_size: 4
embedding_dim: 4
ent_embedding_dim: 50
rel_embedding_dim: 50

num_epochs: 50
patience: 5

