run_name: pan

seed: 19
is_debug: True

optimizer:
  _target_: torch.optim.Adam
  _mode_: partial
  lr: 0.0001

alpha: 0.2
logit_to_prob: "sigmoid"

dataset: "FB15k237"
model: "complex"
batch_size: 64
eval_batch_size: 4
embedding_dim: 4

num_epochs: 50
patience: 5

