project: pu_graphs
entity: hse-jbr-ai
sweep: loss-sweep-debug

program: main.py

metric:
  name: mrr_filtered_epoch/test
  goal: maximize

method: grid
parameters:
  alpha:
    values:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1.0
  logit_to_prob:
    values:
      - "sigmoid"
      - "learnable"
