project: pu_graphs
entity: hse-jbr-ai
name: pan-FB15k237-grad-clip

program: main_pan.py

metric:
  name: mrr_filtered_epoch/test
  goal: maximize

method: grid
parameters:
  dataset:
    value: "WN18RR"
  model:
    value: "complex"
  alpha:
    value: 0.001
  grad_clip_max_norm:
    values:
      - 1.0
      - 2.0
      - 5.0
      - 10.0
  eval_metric_key:
    values:
      - "mrr_filtered"
      - "loss_disc"
  logit_to_prob:
    value: "sigmoid"
