project: pu_graphs
entity: hse-jbr-ai
sweep: pan-WN18RR

program: main_pan.py

metric:
  name: mrr_filtered_epoch/test
  goal: maximize

method: grid
parameters:
  dataset:
    value: "WN18RR"
  model:
    value: "complex"
  alpha:
    value: 0.01
  max_norm:
    values:
      - 1.0
      - 2.0
      - 3.0
  eval_metric_key:
    values:
      - "mrr_filtered"
      - "loss_disc"
  logit_to_prob:
    value: "sigmoid"
