project: pu_graphs
entity: hse-jbr-ai
sweep: pan-WN18RR

program: main_pan.py

metric:
  name: mrr_filtered_epoch/test
  goal: maximize

method: grid
parameters:
  dataset:
    value: "WN18RR"
  model:
    values:
      - "distmult"
      - "complex"
  alpha:
    values:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
  logit_to_prob:
    values:
      - "sigmoid"
      - "learnable"
